### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by yuchunc** [elixirtw/elixir_tw#4]
- 使用者登入
  我原本想說可以用 username + password + 多個Oauth (github, facebook), 不過UI 的 flow 上會比較繁瑣，所以先只用好FB登入 (可以很快地換到 github)。
  - [ ] Username + Password + reCAPTCHA
  - [x] Facebook Oauth
  - [ ] Github Oauth
  - [x] 使用者可以顯示 [Gravatar](http://en.gravatar.com/) or Default Logo
- 發文
  - [x] 使用者可以發文
  - [x] 文章有 slug
  - [x] ~~文章有 Excerpt，可以自定義或是~~ Excerpt 擷取 body前 150 個字元
  - [x] 文章可以由Admin 置頂
  - [ ] 文章用Markdown編輯
  - [ ] 從圖片url load 圖片
  - [ ] 可以預覽文章
  - [ ] 文章有Tag
  - [ ] Tags 為系統預定 (Announcements, Jobs, Tutorials ... 其他再想想，大概四五個就好)
  - [ ] Maybe Emoji?
- 回文
  - [ ] 或許可以直接用Post 來存，利用類似 commented_id + position 來存對應的回文。 
  - [ ] 回文一樣適用 Markdown 來編輯
- 版面
  - [x] Landing Page
  - [ ] 顯示所有的Post
  - [ ] 每個 Tag 都有對應的 Tabs 可以切換過去，只顯示有那個 Tag 的 Posts
  - [ ] 一次只顯示N個 Posts (Pagination)
  - [ ] 閱讀文章的頁面
  - [ ] 文章能夠Comment
- OPs
  - [ ] 找地方 Host (Digital Ocean)
  - [x] deployment
  - [ ] 加入 Google Analytics 
  - [ ] https
  - [ ] license

**Comment by yuchunc** [comment]
@taiansu @otaq 兩位可以看一下~ = ) 我們可以在這邊或是 slack 上討論

**Comment by yuchunc** [comment]
deployment 搞不定 npm Orz
不過至少有東西上去 server 了.... 先將吧....

歡迎高手協助！

**Comment by otaq** [comment]
如果能把 TODOs 拆成 issue，要解 issue 的貢獻者可以在 issue 內認領，也可以在 issue 回報遇到的問題，像是手上要做的 issue 被另外一個 issue 卡著，或者在解 issue 時又出現另外一個 issue 之類的問題。

那麼就可以降低同時有多人再解同一個 issue 的機率，同時也能夠讓貢獻者了解專案目前的情況。

各位覺得這麼做好嗎？

**Comment by yuchunc** [comment]
這樣很好！
可以再由主要的 Maintainer 來維持這份的正確性。

現在這上面應該基本功能都有了，只是還不能 Comment ，目前這上面的都解完 我們應該就有 v1 了。

**Comment by yuchunc** [comment]
開 Project 囉! 
https://github.com/elixirtw/elixir_tw/projects/1

**Comment by yuchunc** [comment]
Closing old inactive issue
